name: Bonjour
on:
  - push
jobs:
  dire_bonjour:
    runs-on: ubuntu-22.04
    env:
      IMAGE_NAME: "mynode:19"
    steps:
      - name: Checkout repository code 
        uses: actions/checkout@v3
      - run: docker image build --tag="${IMAGE_NAME}" .
      - run: echo "Hello World" >> index.js
      - run: docker container run --rm --workdir="$(pwd)" --volume="$(pwd)":"$(pwd)" "${IMAGE_NAME}" npm run lint
